add_rules("mode.debug", "mode.release", "mode.profile")

target("plume-vm")
  add_files("src/**.c")
  add_includedirs("include")
  set_kind("binary") 
  set_targetdir("bin")
  set_optimize("fastest")

target("plume-vm-test")
  add_files("src/**.c")
  add_includedirs("include")
  set_kind("binary") 
  set_symbols("debug")
  add_cxflags("-pg")
  add_ldflags("-pg")
