package("plume")
  set_urls("https://github.com/plume-lang/runtime.git")
  set_license("MIT")
  add_deps("plume-vm")
  on_install(function (package)
    os.cp("include", package:installdir())
  end)

target("plume-vm")
  add_rules("mode.release")
  add_files("src/**.c")
  add_includedirs("include")
  set_kind("binary") 
  set_targetdir("bin")
  set_optimize("fastest")

target("plume-vm-test")
  add_rules("mode.debug", "mode.profile")
  add_files("src/**.c")
  add_includedirs("include")
  set_kind("binary") 
  set_symbols("debug")
  add_cxflags("-pg")
  add_ldflags("-pg")
